//
//  RegisterRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 26/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class RegisterRouter: RegisterWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RegisterViewController(nibName: nil, bundle: nil)
        let interactor = RegisterInteractor()
        let router = RegisterRouter()
        let presenter = RegisterPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goBack() {
        guard let nav = self.viewController?.navigationController else {return}
        nav.popViewController(animated: true)
    }
    
    func gotoRequestScreen() {
        guard let nav = self.viewController?.navigationController else {return}
        let controller = CongratulationJobRouter.createModule(.request)
        nav.pushViewController(controller, animated: true)
    }
    
}
