//
//  MyJobsProtocols.swift
//  HYDD-driver
//
//  Created Syed Kashan on 06/02/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation
enum TVType {
    case progress, completed
}
// MARK: Wireframe -
protocol MyJobsWireframeProtocol: class {
    func gotoStartJob(data: CarSummaryModel)
}
// MARK: Presenter -
protocol MyJobsPresenterProtocol: class {

    var interactor: MyJobsInteractorInputProtocol? { get set }
    var screenView: TVType? {get set}
    
    var missionList: [CarSummaryModel]? {get set}
    
    func selectedData(index: IndexPath)
    func getMyMissions(progress: Bool)
}

// MARK: Interactor -
protocol MyJobsInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func success(data: [CarSummaryModel])
    func failure(message: String)
}

protocol MyJobsInteractorInputProtocol: class {

    var presenter: MyJobsInteractorOutputProtocol? { get set }

    func getMyMissions(progress: Bool)
    /* Presenter -> Interactor */
}

// MARK: View -
protocol MyJobsViewProtocol: class {

    var presenter: MyJobsPresenterProtocol? { get set }
    
    func reloadView()
    func showLoader()
    func hideLoader()
    func setEmptyMessage(text: String)

    /* Presenter -> ViewController */
}
