//
//  MyJobsPresenter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 06/02/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyJobsPresenter: MyJobsPresenterProtocol, MyJobsInteractorOutputProtocol {
    var missionList: [CarSummaryModel]?
 
    var screenView: TVType?

    weak private var view: MyJobsViewProtocol?
    var interactor: MyJobsInteractorInputProtocol?
    private let router: MyJobsWireframeProtocol

    init(interface: MyJobsViewProtocol, interactor: MyJobsInteractorInputProtocol?, router: MyJobsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func selectedData(index: IndexPath) {
        guard let data = self.missionList?[index.row] else {return}
        self.router.gotoStartJob(data: data)
    }
    
    func getMyMissions(progress: Bool) {
        view?.showLoader()
        missionList?.removeAll()
        interactor?.getMyMissions(progress: progress)
    }
    
    func success(data: [CarSummaryModel]) {
        view?.hideLoader()
        missionList = []
        missionList = data
        view?.setEmptyMessage(text: "")
        view?.reloadView()
    }
    
    func failure(message: String) {
        view?.hideLoader()
        view?.setEmptyMessage(text: message)
        view?.reloadView()
    }
}
