//
//  ChatListInteractor.swift
//  HYDD-driver
//
//  Created Macbook Pro on 07/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ChatListInteractor: ChatListInteractorInputProtocol {

    weak var presenter: ChatListInteractorOutputProtocol?
}
