//
//  ChatListPresenter.swift
//  HYDD-driver
//
//  Created Macbook Pro on 07/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ChatListPresenter: ChatListPresenterProtocol, ChatListInteractorOutputProtocol {

    weak private var view: ChatListViewProtocol?
    var interactor: ChatListInteractorInputProtocol?
    private let router: ChatListWireframeProtocol

    init(interface: ChatListViewProtocol, interactor: ChatListInteractorInputProtocol?, router: ChatListWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func showChat(idClient: Int, image: String, userName: String) {
        router.showChat(idClient: idClient, image: image, userName: userName)
    }

}
