//
//  ChatListRouter.swift
//  HYDD-driver
//
//  Created Macbook Pro on 07/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ChatListRouter: ChatListWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ChatListViewController(nibName: nil, bundle: nil)
        let interactor = ChatListInteractor()
        let router = ChatListRouter()
        let presenter = ChatListPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func showChat(idClient: Int, image: String, userName: String) {
        guard let nav = self.viewController?.navigationController else {return}
        let controller = ChatRouter.createModule(idClient, userName, image, .chatList)
        nav.pushViewController(controller, animated: true)
    }
}
