//
//  ChatListProtocols.swift
//  HYDD-driver
//
//  Created Macbook Pro on 07/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

// MARK: Wireframe -
protocol ChatListWireframeProtocol: class {
    func showChat(idClient: Int, image: String, userName: String)
}
// MARK: Presenter -
protocol ChatListPresenterProtocol: class {

    var interactor: ChatListInteractorInputProtocol? { get set }    
    func showChat(idClient: Int, image: String, userName: String)
    
}

// MARK: Interactor -
protocol ChatListInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ChatListInteractorInputProtocol: class {

    var presenter: ChatListInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
    
}

// MARK: View -
protocol ChatListViewProtocol: class {

    var presenter: ChatListPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
