//
//  EmailVerifyRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 01/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class EmailVerifyRouter: EmailVerifyWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = EmailVerifyViewController(nibName: nil, bundle: nil)
        let interactor = EmailVerifyInteractor()
        let router = EmailVerifyRouter()
        let presenter = EmailVerifyPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goBack() {
        
    }
    
}
