//
//  MyCarInteractor.swift
//  HYDD-driver
//
//  Created Macbook Pro on 18/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyCarInteractor: MyCarInteractorInputProtocol {
    
    weak var presenter: MyCarInteractorOutputProtocol?
}
