//
//  ChangePasswordPresenter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 01/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ChangePasswordPresenter: ChangePasswordPresenterProtocol, ChangePasswordInteractorOutputProtocol {
    
    var oldPassword: String?

    weak private var view: ChangePasswordViewProtocol?
    var interactor: ChangePasswordInteractorInputProtocol?
    private let router: ChangePasswordWireframeProtocol

    init(interface: ChangePasswordViewProtocol, interactor: ChangePasswordInteractorInputProtocol?, router: ChangePasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func set(password: String) {
        self.oldPassword = password
    }
    
    func verifyPassword() {
        
        guard let password = self.oldPassword else {return}
        if password.isValidPassword {
            view?.showLoader()
            interactor?.verify(password: password)
        } else {
            HMM.shared.showWarning(title: DJM.shared.getValue(view: "change_password_view", variable: "warning"), message: DJM.shared.getValue(view: "change_password_view", variable: "password_condition"))
        }
        
    }
    
    func successVerify() {
        self.view?.hideLoader()
        DispatchQueue.main.async {
            guard let password = self.oldPassword else {return}
            self.router.gotoVerify(old: password)
        }
    }
    
    func failedVerify() {
        self.view?.hideLoader()
    }
}
