//
//  ChangePasswordInteractor.swift
//  HYDD-driver
//
//  Created Syed Kashan on 01/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ChangePasswordInteractor: ChangePasswordInteractorInputProtocol {
    
    weak var presenter: ChangePasswordInteractorOutputProtocol?
    
    static let apiClient = APIClient()
    var verifyTask: URLSessionDataTask!
    
    func verify(password: String) {
        guard let id = HUM.shared.user?.id else {return}
        HUM.shared.getToken { isSuccess in
            if isSuccess{
                self.verifyTask?.cancel()
                let para = ["password": password]
                let verifyReq = URLRequest(url: NETWORKCONSTANTS.verifyPassword(id: id),
                                           method: URLRequest.HTTPMethod.put,
                                           body: para)
                self.verifyTask = ChangePasswordInteractor.apiClient.dataTask(verifyReq) {[weak self] response in
                    //Response
                    response.successResponse.flatMap { (data, response) in
                        printHydd("Response is \(data) \nResponse \(response)")
                        printHydd(String(decoding: data, as: UTF8.self))
                        if let dataDictionary = data.getJSONFromData() {
                            if let message = dataDictionary["message"] as? String {
                                HMM.shared.showError(title: DJM.shared.getValue(view: "change_password_view", variable: "error"), message: message)
                                self?.presenter?.failedVerify()
                            } else {
                                self?.presenter?.successVerify()
                            }
                        } else {
                            self?.presenter?.failedVerify()
                        }
                    }
                }
            }
        }
    }
}
