//
//  ChangePasswordProtocols.swift
//  HYDD-driver
//
//  Created Syed Kashan on 01/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

// MARK: Wireframe -
protocol ChangePasswordWireframeProtocol: class {
    func gotoVerify(old: String)

}
// MARK: Presenter -
protocol ChangePasswordPresenterProtocol: class {

    var interactor: ChangePasswordInteractorInputProtocol? { get set }
    var oldPassword: String? {get set}
    
    func set(password: String)
    func verifyPassword()
}

// MARK: Interactor -
protocol ChangePasswordInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func successVerify()
    func failedVerify()
}

protocol ChangePasswordInteractorInputProtocol: class {

    var presenter: ChangePasswordInteractorOutputProtocol? { get set }

    func verify(password: String)
    /* Presenter -> Interactor */
}

// MARK: View -
protocol ChangePasswordViewProtocol: class {

    var presenter: ChangePasswordPresenterProtocol? { get set }

    func showLoader()
    func hideLoader()
    /* Presenter -> ViewController */
}
