//
//  SideMenuRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 26/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class SideMenuRouter: SideMenuWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(screenType: SideMenu ) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SideMenuViewController(nibName: nil, bundle: nil)
        let interactor = SideMenuInteractor()
        let router = SideMenuRouter()
        let presenter = SideMenuPresenter(interface: view, interactor: interactor, router: router)

        presenter.screenType = screenType
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    func gotoNewJob() {
        Bootstrapper.gotoJobList()
    }
    func gotoJob() {
        Bootstrapper.gotoInProgessJobs()
    }
    func gotoChat() {
//        guard let nav = self.viewController?.navigationController else { return }
//        let jobList = JobListingRouter.createModule()
//        nav.pushViewController(jobList, animated: true)
    }
    
    func gotoProfile() {
        Bootstrapper.showProfile()
    }
    
    func gotoEarning() {
        Bootstrapper.gotoEarnings()
    }
}
