//
//  SideMenuProtocols.swift
//  HYDD-driver
//
//  Created Syed Kashan on 26/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

// MARK: Wireframe -
protocol SideMenuWireframeProtocol: class {
    func gotoNewJob()
    func gotoJob()
    func gotoChat()
    func gotoEarning()
    func gotoProfile()
}
// MARK: Presenter -
protocol SideMenuPresenterProtocol: class {

    var interactor: SideMenuInteractorInputProtocol? { get set }
    
    var sideMenuData: [SideMenuModel]? {get set}
    
    func setInitialSideMenu()
    func gotoTab(indexpath: IndexPath)
    func showProfile()
}

// MARK: Interactor -
protocol SideMenuInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SideMenuInteractorInputProtocol: class {

    var presenter: SideMenuInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol SideMenuViewProtocol: class {

    var presenter: SideMenuPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
