//
//  SideMenuViewController.swift
//  HYDD-driver
//
//  Created Syed Kashan on 26/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class SideMenuViewController: BaseViewController, SideMenuViewProtocol {

    @IBOutlet weak var imageUser: UIImageView!
    @IBOutlet weak var labelName: UILabel!
    @IBOutlet weak var tableViewSideMenu: UITableView!
    
    var presenter: SideMenuPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.setupView()
        
    }
    @IBAction func actionProfile(_ sender: UIButton) {
        self.presenter?.showProfile()
    }
    func reloadTable() {
        self.tableViewSideMenu.reloadData()
    }
}

extension SideMenuViewController : SetupViewController {
    func setupNavigation() {
    }
    
    func setupView() {
        presenter?.setInitialSideMenu()
        tableViewSideMenu.dataSource = self
        tableViewSideMenu.delegate = self
        tableViewSideMenu.register(UINib(nibName: "SideMenuTableViewCell", bundle: nil), forCellReuseIdentifier: "SideMenuTableViewCell")
        labelName.attributedText = HUM.shared.user?.username.styled(as: .gibsonRegular_18sp)
        DispatchQueue.main.async {
            guard let image = HUM.shared.user?.userImage, image.count > 5 else { return }
            ImageManager.shared.setImage(url: image, imageView: self.imageUser)
            self.imageUser.makeRoundedImage()
        }
    }
    
    func networkRequest() {
    }
}

extension SideMenuViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        self.presenter?.gotoTab(indexpath: indexPath)
    }
    
}

extension SideMenuViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let count = self.presenter?.sideMenuData?.count else {return 0}
        return count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableViewSideMenu.dequeueReusableCell(withIdentifier: "SideMenuTableViewCell") as? SideMenuTableViewCell else {return UITableViewCell()}
        guard let data = self.presenter?.sideMenuData?[indexPath.row] else {return cell}
        cell.configureCell(object: data)
        return cell
    }
    
    
}
