//
//  SideMenuInteractor.swift
//  HYDD-driver
//
//  Created Syed Kashan on 26/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class SideMenuInteractor: SideMenuInteractorInputProtocol {

    weak var presenter: SideMenuInteractorOutputProtocol?
}
