//
//  ChatProtocols.swift
//  HYDD-driver
//
//  Created Macbook Pro on 21/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

enum ScreenType {
    case chatList, map, pushNotification
}

// MARK: Wireframe -
protocol ChatWireframeProtocol: class {
    func goBack()
}
// MARK: Presenter -
protocol ChatPresenterProtocol: class {

    var interactor: ChatInteractorInputProtocol? { get set }
    func goBack()
    func sendNotification(para: [String: Any])
}

// MARK: Interactor -
protocol ChatInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ChatInteractorInputProtocol: class {

    var presenter: ChatInteractorOutputProtocol? { get set }
    
    func sendNotification(para: [String: Any])
    /* Presenter -> Interactor */
}

// MARK: View -
protocol ChatViewProtocol: class {

    var presenter: ChatPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
