//
//  ChatRouter.swift
//  HYDD-driver
//
//  Created Macbook Pro on 21/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ChatRouter: ChatWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(_ id: Int = 0, _ username: String = "", _ userImage: String = "", _ from: ScreenType = .map) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ChatViewController(nibName: nil, bundle: nil)
        let interactor = ChatInteractor()
        let router = ChatRouter()
        let presenter = ChatPresenter(interface: view, interactor: interactor, router: router)

        view.setView(id: id, image: userImage, username: username, viewType: from)
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goBack() {
        guard let nav = self.viewController?.navigationController else {return}
        nav.popViewController(animated: true)
    }
    
}
