//
//  ChatInteractor.swift
//  HYDD-driver
//
//  Created Macbook Pro on 21/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ChatInteractor: ChatInteractorInputProtocol {
    
    weak var presenter: ChatInteractorOutputProtocol?
    
    static let apiClient = APIClient()
    var sendPNTask: URLSessionDataTask!
    
    func sendNotification(para: [String : Any]) {
        HUM.shared.getToken { isSuccess in
            if isSuccess{
                self.sendPNTask?.cancel()
                let pnUrl = URLRequest(url: NETWORKCONSTANTS.chatPN(),
                                       method: URLRequest.HTTPMethod.post,
                                       body: para)
                self.sendPNTask = ChatInteractor.apiClient.dataTask(pnUrl) {response in
                    //Response
                    response.successResponse.flatMap { (data, response) in
                        printHydd("Response is \(data) \nResponse \(response)")
                        printHydd(String(decoding: data, as: UTF8.self))
                    }
                }
            }
        }
    }
}
