//
//  NavigationPopUpInteractor.swift
//  HYDD-driver
//
//  Created Kashan on 12/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class NavigationPopUpInteractor: NavigationPopUpInteractorInputProtocol {

    weak var presenter: NavigationPopUpInteractorOutputProtocol?
}
