//
//  NavigationPopUpPresenter.swift
//  HYDD-driver
//
//  Created Kashan on 12/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan

import UIKit

class NavigationPopUpPresenter: NavigationPopUpPresenterProtocol, NavigationPopUpInteractorOutputProtocol {

    weak private var view: NavigationPopUpViewProtocol?
    var interactor: NavigationPopUpInteractorInputProtocol?
    private let router: NavigationPopUpWireframeProtocol

    init(interface: NavigationPopUpViewProtocol, interactor: NavigationPopUpInteractorInputProtocol?, router: NavigationPopUpWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
