//
//  NavigationPopUpRouter.swift
//  HYDD-driver
//
//  Created Kashan on 12/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan


import UIKit

class NavigationPopUpRouter: NavigationPopUpWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(_ delegate: NavigationPopupDelegate? = nil) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = NavigationPopUpViewController(nibName: nil, bundle: nil)
        let interactor = NavigationPopUpInteractor()
        let router = NavigationPopUpRouter()
        let presenter = NavigationPopUpPresenter(interface: view, interactor: interactor, router: router)

        view.delegate = delegate
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
