//
//  JobListingRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 26/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class JobListingRouter: JobListingWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = JobListingViewController(nibName: nil, bundle: nil)
        let interactor = JobListingInteractor()
        let router = JobListingRouter()
        let presenter = JobListingPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func showAcceptScreen(data: CarSummaryModel) {
        guard let nav = self.viewController?.navigationController else {return}
        let controller = StartJobRouter.createModule(.listing, dataList: data)
        nav.pushViewController(controller, animated: true)
    }
    
}
