//
//  JobListingProtocols.swift
//  HYDD-driver
//
//  Created Syed Kashan on 26/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

// MARK: Wireframe -
protocol JobListingWireframeProtocol: class {
    func showAcceptScreen(data: CarSummaryModel)
}
// MARK: Presenter -
protocol JobListingPresenterProtocol: class {

    var interactor: JobListingInteractorInputProtocol? { get set }
    var missionData: [CarSummaryModel]? {get set}
    
    func selectedJob(index: IndexPath)
    func getNewMissions()
}

// MARK: Interactor -
protocol JobListingInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func successFound(data: [CarSummaryModel])
    func failureFound(message: String)
}

protocol JobListingInteractorInputProtocol: class {

    var presenter: JobListingInteractorOutputProtocol? { get set }

    func getNewMissions()
    /* Presenter -> Interactor */
}

// MARK: View -
protocol JobListingViewProtocol: class {

    var presenter: JobListingPresenterProtocol? { get set }

    func reloadData()
    func showLoader()
    func hideLoader()
    func showNoData(message: String)
    /* Presenter -> ViewController */
}
