//
//  MyEarningsRouter.swift
//  HYDD-driver
//
//  Created Macbook Pro on 14/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyEarningsRouter: MyEarningsWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MyEarningsViewController(nibName: nil, bundle: nil)
        let interactor = MyEarningsInteractor()
        let router = MyEarningsRouter()
        let presenter = MyEarningsPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
