//
//  MyEarningsInteractor.swift
//  HYDD-driver
//
//  Created Macbook Pro on 14/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyEarningsInteractor: MyEarningsInteractorInputProtocol {
    
    static let apiClient = APIClient()
    var earningTask: URLSessionDataTask!
    
    weak var presenter: MyEarningsInteractorOutputProtocol?
    
    func getData() {
        guard let id = HUM.shared.user?.id else {return}
        HUM.shared.getToken { isSuccess in
            if isSuccess{
                self.earningTask?.cancel()
                let earning = URLRequest(url: NETWORKCONSTANTS.myEarnings(id: id),
                                         method: URLRequest.HTTPMethod.get,
                                         body: nil)
                self.earningTask = MyEarningsInteractor.apiClient.dataTask(earning) {[weak self] response in
                    //Response
                    response.successResponse.flatMap { (data, response) in
                        printHydd("Response is \(data) \nResponse \(response)")
                        printHydd(String(decoding: data, as: UTF8.self))
                        if let dataDictionary = data.getJSONFromData() {
                            if let message = dataDictionary["message"] as? String {
                                self?.presenter?.failedData(message: message)
                            } else {
                                if let data = dataDictionary["data"] as? [String: Any] {
                                    if let earningRes = Earning(JSON: data) {
                                        self?.presenter?.successData(earnings: earningRes)
                                    }
                                } else {
                                    self?.presenter?.failedData(message: DJM.shared.getValue(view: "earnings_view", variable: "went_wrong"))
                                }
                            }
                        } else {
                            self?.presenter?.failedData(message: DJM.shared.getValue(view: "earnings_view", variable: "went_wrong"))
                        }
                    }
                }
            }
        }
    }
}

