//
//  MyEarningsProtocols.swift
//  HYDD-driver
//
//  Created Macbook Pro on 14/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

enum ScreenTypeEarning {
    case day, week, month
}

// MARK: Wireframe -
protocol MyEarningsWireframeProtocol: class {

}
// MARK: Presenter -
protocol MyEarningsPresenterProtocol: class {

    var interactor: MyEarningsInteractorInputProtocol? { get set }
    
    var earning: Earning? { get set }
    var screenType: ScreenTypeEarning? {get set}
    var selectedTime: Int? {get set}
    
    func setInitialData()
    func setScreenType(screen: ScreenTypeEarning)
    func setSelectedTime(time: String)
}

// MARK: Interactor -
protocol MyEarningsInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    
    func successData(earnings: Earning)
    func failedData(message: String)
}

protocol MyEarningsInteractorInputProtocol: class {

    var presenter: MyEarningsInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
    func getData()
}

// MARK: View -
protocol MyEarningsViewProtocol: class {

    var presenter: MyEarningsPresenterProtocol? { get set }
    
    func showHideLeftButton(show: Bool)
    func showHideRightButton(show: Bool)
    
    func reloadContent()
    func showLoader()
    func hideLoader()

    /* Presenter -> ViewController */
}
