//
//  OtherInteractor.swift
//  HYDD-driver
//
//  Created Syed Kashan on 04/06/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class OtherInteractor: OtherInteractorInputProtocol {

    weak var presenter: OtherInteractorOutputProtocol?
}
