//
//  OtherRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 04/06/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class OtherRouter: OtherWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = OtherViewController(nibName: nil, bundle: nil)
        let interactor = OtherInteractor()
        let router = OtherRouter()
        let presenter = OtherPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
