//
//  OtherPresenter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 04/06/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class OtherPresenter: OtherPresenterProtocol, OtherInteractorOutputProtocol {

    weak private var view: OtherViewProtocol?
    var interactor: OtherInteractorInputProtocol?
    private let router: OtherWireframeProtocol

    init(interface: OtherViewProtocol, interactor: OtherInteractorInputProtocol?, router: OtherWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
