//
//  StartJobPopUpViewController.swift
//  HYDD-driver
//
//  Created Syed Kashan on 10/02/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class StartJobPopUp: UIView {

    @IBOutlet weak var viewNo: UIView!
    @IBOutlet weak var viewYes: UIView!
    @IBOutlet weak var labelDescription: UILabel!
    @IBOutlet weak var textFieldCar: UITextField!
    @IBOutlet weak var buttonYes: UIButton!
    @IBOutlet weak var buttonNo: UIButton!
    @IBOutlet weak var viewCorner: UIView!
    
    var car: MyCarDetailModel?
    var myVehicles: [MyCarDetailModel]?
    
    override func awakeFromNib() {
        super.awakeFromNib()
        textFieldCar.delegate = self
        giveBtnCornerRadiusWithTheDarkBackGround(view: viewYes, btn: buttonYes)
        giveBtnCornerRadiusWithTheDarkBackGround(view: viewNo, btn: buttonNo,type: .cancel)
        textFieldCar.setLeftPaddingPoints(15)
        let attDescription = DJM.shared.getValue(view: "popups_view", variable: "start_1").styled(as: .helveticaRegular_19sp_gray)
        attDescription.append(DJM.shared.getValue(view: "popups_view", variable: "start_2").styled(as: .helveticaRegular_19sp_gray))
        attDescription.append(DJM.shared.getValue(view: "popups_view", variable: "start_3").styled(as: .helveticaRegular_19sp_gray))
        labelDescription.attributedText = attDescription
        
        buttonNo.setAttributedTitle(DJM.shared.getValue(view: "popups_view", variable: "no").styled(as: .helveticaRegular_20sp), for: .normal)
        buttonNo.backgroundColor = .hyddRed
        
        buttonYes.setAttributedTitle(DJM.shared.getValue(view: "popups_view", variable: "yes").styled(as: .helveticaRegular_20sp), for: .normal)
        buttonYes.backgroundColor = .hyddblue
        
        let pickerViewCar = UIPickerView()
        pickerViewCar.delegate = self
        pickerViewCar.dataSource = self
        textFieldCar.inputView = pickerViewCar
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        viewCorner.cornerRadius(cornerRadius: 10)
        buttonYes.cornerRadius(cornerRadius: 6)
        buttonNo.cornerRadius(cornerRadius: 6)
    }
    
    func setClass(vehicleClass: String) {
        self.myVehicles = HCM.shared.getCarsOfMyClass(vehicleClass: vehicleClass)
    }

}

extension StartJobPopUp: UIPickerViewDelegate {
    func pickerView(_ pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        textFieldCar.attributedText = myVehicles?[row].numberPlate.styled(as: .gibsonRegular_15sp) ?? "".styled(as: .gibsonRegular_15sp)
        car = myVehicles?[row]
    }
}
extension StartJobPopUp: UIPickerViewDataSource {
    func numberOfComponents(in pickerView: UIPickerView) -> Int {
        return 1
    }
    
    func pickerView(_ pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        guard let data = myVehicles else {return 0}
        return data.count
    }
    
    func pickerView(_ pickerView: UIPickerView, attributedTitleForRow row: Int, forComponent component: Int) -> NSAttributedString? {
        guard let data = myVehicles?[row].numberPlate else {return "".styled(as: .gibsonRegular_15sp)}
        return "\(data)".styled(as: .gibsonRegular_15sp)
    }
}

extension StartJobPopUp: UITextFieldDelegate {
    func textFieldDidBeginEditing(_ textField: UITextField) {
        if textField.text?.count ?? 0 < 1 {
            textFieldCar.attributedText = myVehicles?[0].numberPlate.styled(as: .gibsonRegular_15sp) ?? "".styled(as: .gibsonRegular_15sp)
            car = myVehicles?[0]
        }
    }
}
