//
//  MyProfileInteractor.swift
//  HYDD-driver
//
//  Created Macbook Pro on 15/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyProfileInteractor: MyProfileInteractorInputProtocol {

    weak var presenter: MyProfileInteractorOutputProtocol?
    
    func updateProfile(para: [String: Any]) {
        HUM.shared.editProfile(para: para) { (isSuccess, message) in
            if isSuccess {
                self.presenter?.successUpdate()
            } else {
                self.presenter?.failedUpdate(error: message)
            }
        }
    }
}
