//
//  MyProfileRouter.swift
//  HYDD-driver
//
//  Created Macbook Pro on 15/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyProfileRouter: MyProfileWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MyProfileViewController(nibName: nil, bundle: nil)
        let interactor = MyProfileInteractor()
        let router = MyProfileRouter()
        let presenter = MyProfilePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func gotoEmailVerify() {
        guard let nav = self.viewController?.navigationController else {return}
        let controller = EmailVerifyRouter.createModule()
        nav.pushViewController(controller, animated: true)
    }
    
    func gotoPassword() {
        guard let nav = self.viewController?.navigationController else {return}
        let controller = ChangePasswordRouter.createModule()
        nav.pushViewController(controller, animated: true)
    }
    
    func gotoCarSelect() {
        guard let nav = self.viewController?.navigationController else {return}
        let controller = MyCarRouter.createModule()
        nav.pushViewController(controller, animated: true)
    }
    
}
