//
//  CongratulationJobViewController.swift
//  HYDD-driver
//
//  Created Syed Kashan on 24/02/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class CongratulationJobViewController: BaseViewController, CongratulationJobViewProtocol {
    
    @IBOutlet weak var viewYes: UIView!
    @IBOutlet weak var tableViewText: UITableView!
    @IBOutlet weak var labelCongratulation: UILabel!
    @IBOutlet weak var buttonOk: UIButton!
    @IBOutlet weak var imageCongratulation: UIImageView!
    
    var presenter: CongratulationJobPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        setupNavigation()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.tabBarController?.tabBar.isHidden = true
    }
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.navigationController?.tabBarController?.tabBar.isHidden = false
    }
    @IBAction func actionOk(_ sender: UIButton) {
        self.presenter?.actionOK()
    }
    
    @IBAction func gotoMenu(_ sender: UIButton) {
        SSMM.shared.showSideMenu(screenType: .newJob)
    }
}

extension CongratulationJobViewController: SetupViewController {
    func setupNavigation() {
        navigationController?.setNavigationBarHidden(false, animated: false)
        setNavigationWithLogoAndMenuButton()
    }
    
    func setupView() {
        giveBtnCornerRadiusWithTheDarkBackGround(view: viewYes, btn: buttonOk)
        tableViewText.delegate = self
        tableViewText.dataSource = self
        guard let type = self.presenter?.screenType else { return}
        switch type {
        case .congratulation:
            labelCongratulation.attributedText = DJM.shared.getValue(view: "congratulate_view", variable: "congratulate").styled(as: .gibsonRegular_40sp_blue)
            imageCongratulation.image = UIImage(named: "icon_congratulations")
        case .request:
            labelCongratulation.attributedText = DJM.shared.getValue(view: "congratulate_view", variable: "sent").styled(as: .gibsonRegular_40sp_blue)
            imageCongratulation.image = UIImage(named: "icon_request_sent")
        }
        buttonOk.backgroundColor = .hyddblue
        buttonOk.setAttributedTitle(DJM.shared.getValue(view: "congratulate_view", variable: "ok").styled(as: .helveticaRegular_20sp), for: .normal)
        buttonOk.roundCorners(6)
    }
    
    func networkRequest() {
    }
}

extension CongratulationJobViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = UITableViewCell()
        cell.backgroundColor = .clear
        guard let type = self.presenter?.screenType else { return UITableViewCell()}
        switch type {
        case .congratulation:
            cell.textLabel?.attributedText = DJM.shared.getValue(view: "congratulate_view", variable: "assigned_job").styled(as: .gibsonRegular_16sp_gray)
        case .request:
            cell.textLabel?.attributedText = DJM.shared.getValue(view: "congratulate_view", variable: "request_job").styled(as: .gibsonRegular_16sp_gray)
        }
        cell.selectionStyle = .none
        cell.textLabel?.numberOfLines = 0
        return cell
    }
    
    
}
