//
//  CongratulationJobProtocols.swift
//  HYDD-driver
//
//  Created Syed Kashan on 24/02/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation
enum ScreenTypeCongratulation {
    case congratulation, request
}
// MARK: Wireframe -
protocol CongratulationJobWireframeProtocol: class {
    func showNewJobs()
    func actionOK()
}
// MARK: Presenter -
protocol CongratulationJobPresenterProtocol: class {

    var interactor: CongratulationJobInteractorInputProtocol? { get set }
    var screenType: ScreenTypeCongratulation? {get set}
    
    func actionOK()
}

// MARK: Interactor -
protocol CongratulationJobInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol CongratulationJobInteractorInputProtocol: class {

    var presenter: CongratulationJobInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol CongratulationJobViewProtocol: class {

    var presenter: CongratulationJobPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
