//
//  CongratulationJobInteractor.swift
//  HYDD-driver
//
//  Created Syed Kashan on 24/02/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class CongratulationJobInteractor: CongratulationJobInteractorInputProtocol {

    weak var presenter: CongratulationJobInteractorOutputProtocol?
}
