//
//  CongratulationJobRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 24/02/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class CongratulationJobRouter: CongratulationJobWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(_ screenType: ScreenTypeCongratulation?) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CongratulationJobViewController(nibName: nil, bundle: nil)
        let interactor = CongratulationJobInteractor()
        let router = CongratulationJobRouter()
        let presenter = CongratulationJobPresenter(interface: view, interactor: interactor, router: router)

        presenter.screenType = screenType
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func actionOK() {
        Bootstrapper.showTabbar(selectedIndex: 1)
    }
    func showNewJobs() {
        Bootstrapper.showTabbar(selectedIndex: 0)
    }
}
