//
//  ForgotPasswordInteractor.swift
//  HYDD-driver
//
//  Created Syed Kashan on 25/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ForgotPasswordInteractor: ForgotPasswordInteractorInputProtocol {

    weak var presenter: ForgotPasswordInteractorOutputProtocol?
    
    static let apiClient = APIClient()
    var forgotTask: URLSessionDataTask!
    
    func reset(email: String) {
        forgotTask?.cancel()
        let para = ["email": email]
        let forgotURL = URLRequest(url: NETWORKCONSTANTS.REGISTRATION.forgot,
                              method: URLRequest.HTTPMethod.post,
                              body: para)
        forgotTask = ForgotPasswordInteractor.apiClient.dataTask(forgotURL) {[weak self] response in
            //Response
            response.successResponse.flatMap { (data, response) in
                printHydd("Response is \(data) \nResponse \(response)")
                printHydd(String(decoding: data, as: UTF8.self))
                if let dataDictionary = data.getJSONFromData() {
                    if let message = dataDictionary["message"] as? String {
                        self?.presenter?.failedRequest(message: message)
                    } else {
                        if let data = dataDictionary["data"] as? String {
                            self?.presenter?.successRequest(message: data)
                        }
                    }
                } else {
                    self?.presenter?.failedRequest(message: DJM.shared.getValue(view:  "forgot_password_view", variable:  "went_wrong"))
                }
            }
        }
    }
}
