//
//  ForgotPasswordRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 25/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ForgotPasswordRouter: ForgotPasswordWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ForgotPasswordViewController(nibName: nil, bundle: nil)
        let interactor = ForgotPasswordInteractor()
        let router = ForgotPasswordRouter()
        let presenter = ForgotPasswordPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goBack() {
        guard let nav = self.viewController?.navigationController else {return}
        nav.popViewController(animated: true)
    }
    
}
