//
//  ForgotPasswordPresenter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 25/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class ForgotPasswordPresenter: ForgotPasswordPresenterProtocol, ForgotPasswordInteractorOutputProtocol {

    var email: String?

    weak private var view: ForgotPasswordViewProtocol?
    var interactor: ForgotPasswordInteractorInputProtocol?
    private let router: ForgotPasswordWireframeProtocol

    init(interface: ForgotPasswordViewProtocol, interactor: ForgotPasswordInteractorInputProtocol?, router: ForgotPasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    
    func goBack() {
        self.router.goBack()
    }
    
    func reset() {
        let (email, isValidEmail) = self.validateEmail()
        if isValidEmail {
            view?.showLoader()
            self.interactor?.reset(email: email)
        }
    }
    
    func successRequest(message: String) {
        view?.hideLoader()
        DispatchQueue.main.async {
            HMM.shared.showStatusSuccess(message: message)
            self.router.goBack()
        }
    }
    
    func failedRequest(message: String) {
        view?.hideLoader()
        DispatchQueue.main.async {
            HMM.shared.showError(title: DJM.shared.getValue(view:  "forgot_password_view", variable:  "error"), message: message)
        }
    }
    
    func set(email: String) {
        self.email = email
    }
    
    func validateEmail()  -> (String, Bool) {
        
        guard let email = self.email else {
            view?.setEmailStatus(error: TfError.emptyEmail, status: .empty)
            return ("", false)
        }
        
        let isEmailValid = email.isValidEmail
        
        isEmailValid ?
            view?.setEmailStatus(error: TfError.none, status: .success) :
            view?.setEmailStatus(error: TfError.invalidEmail, status: .error)
        
        return (email, isEmailValid)
    }
}
