//
//  SigninRouter.swift
//  Hydd
//
//  Created Syed Kashan on 05/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class SigninRouter: SigninWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SigninViewController(nibName: nil, bundle: nil)
        let interactor = SigninInteractor()
        let router = SigninRouter()
        let presenter = SigninPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goBack() {
    }
    
    func showForgotPassword() {
        guard let nav = self.viewController?.navigationController else { return }
//        guard let Signin = self.viewController as? SigninViewController else { return }
        let forgot = ForgotPasswordRouter.createModule()
//        let nav = UINavigationController(rootViewController: forgot)
//        Signin.present(nav, animated: true, completion: nil)
        nav.pushViewController(forgot, animated: true)
    }
    
    func showSignUp() {
        Bootstrapper.showTabbar(selectedIndex: 0)
    }
    
}
