//
//  SigninInteractor.swift
//  Hydd
//
//  Created Syed Kashan on 05/01/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan

import UIKit

class SigninInteractor: SigninInteractorInputProtocol {

    static let apiClient = APIClient()
    var loginTask: URLSessionDataTask!
    
    weak var presenter: SigninInteractorOutputProtocol?
    
    func login(email: String, password: String) {
        loginTask?.cancel()
        let para = ["email": email,
                    "password": password,
                    "device_id": "2j3asdh4-4359-32bdf" ] //APPCONSTANT.GENERAL.userFCMToken
        let login = URLRequest(url: NETWORKCONSTANTS.REGISTRATION.login,
                              method: URLRequest.HTTPMethod.post,
                              body: para as [String: Any])
        loginTask = SigninInteractor.apiClient.dataTask(login) {[weak self] response in
            //Response
            response.successResponse.flatMap { (data, response) in
                printHydd("Response is \(data) \nResponse \(response)")
                printHydd(String(decoding: data, as: UTF8.self))
                if let dataDictionary = data.getJSONFromData() {
                    if let message = dataDictionary["message"] as? String {
                        HMM.shared.showError(title: DJM.shared.getValue(view: "signin_view", variable: "login_error"), message: message)
                        self?.presenter?.failedLogin()
                    } else {
                        if let data = dataDictionary["data"] as? [[String: Any]] {
                            if let user = User(JSON: data[0]) {
                                HUM.shared.getProfile(id: user.id) { isSuccess in
                                    if isSuccess {
                                        self?.presenter?.successLogin()
                                    } else {
                                        self?.presenter?.failedLogin()
                                    }
                                }
                            }
                        } else {
                            self?.presenter?.failedLogin()
                            HMM.shared.showError(title: DJM.shared.getValue(view: "signin_view", variable: "login_error"), message: DJM.shared.getValue(view: "signin_view", variable: "went_wrong"))
                        }
                    }
                } else {
                    self?.presenter?.failedLogin()
                }
            }
        }
    }
}
