//
//  NavigationInteractor.swift
//  HYDD-driver
//
//  Created Macbook Pro on 11/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class NavigationInteractor: NavigationInteractorInputProtocol {

    weak var presenter: NavigationInteractorOutputProtocol?
}
