//
//  NavigationPresenter.swift
//  HYDD-driver
//
//  Created Macbook Pro on 11/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class NavigationPresenter: NavigationPresenterProtocol, NavigationInteractorOutputProtocol {

    weak private var view: NavigationViewProtocol?
    var interactor: NavigationInteractorInputProtocol?
    private let router: NavigationWireframeProtocol

    init(interface: NavigationViewProtocol, interactor: NavigationInteractorInputProtocol?, router: NavigationWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func addPressed() {
        router.addPressed()
    }
    func gotoInProgress() {
        router.gotoInProgress()
    }
    
}
