//
//  NavigationProtocols.swift
//  HYDD-driver
//
//  Created Macbook Pro on 11/04/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

// MARK: Wireframe -
protocol NavigationWireframeProtocol: class {
    func addPressed()
    func gotoInProgress()
}
// MARK: Presenter -
protocol NavigationPresenterProtocol: class {

    var interactor: NavigationInteractorInputProtocol? { get set }
    func addPressed()
    
    func gotoInProgress()
}

// MARK: Interactor -
protocol NavigationInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol NavigationInteractorInputProtocol: class {

    var presenter: NavigationInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol NavigationViewProtocol: class {

    var presenter: NavigationPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
