//
//  RatingsProtocols.swift
//  HYDD-driver
//
//  Created Syed Kashan on 30/06/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

// MARK: Wireframe -
protocol RatingsWireframeProtocol: class {

}
// MARK: Presenter -
protocol RatingsPresenterProtocol: class {

    var interactor: RatingsInteractorInputProtocol? { get set }
}

// MARK: Interactor -
protocol RatingsInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol RatingsInteractorInputProtocol: class {

    var presenter: RatingsInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
}

// MARK: View -
protocol RatingsViewProtocol: class {

    var presenter: RatingsPresenterProtocol? { get set }

    /* Presenter -> ViewController */
}
