//
//  RatingsRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 30/06/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class RatingsRouter: RatingsWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RatingsViewController(nibName: nil, bundle: nil)
        let interactor = RatingsInteractor()
        let router = RatingsRouter()
        let presenter = RatingsPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
