//
//  RatingsInteractor.swift
//  HYDD-driver
//
//  Created Syed Kashan on 30/06/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class RatingsInteractor: RatingsInteractorInputProtocol {

    weak var presenter: RatingsInteractorOutputProtocol?
}
