//
//  MyCarClassDetailRouter.swift
//  HYDD-driver
//
//  Created Macbook Pro on 20/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyCarClassDetailRouter: MyCarClassDetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(_ carData: [MyCarDetailModel]? = nil) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MyCarClassDetailViewController(nibName: nil, bundle: nil)
        let interactor = MyCarClassDetailInteractor()
        let router = MyCarClassDetailRouter()
        let presenter = MyCarClassDetailPresenter(interface: view, interactor: interactor, router: router)

        presenter.carData = carData
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goBack() {
        guard let nav = viewController?.navigationController else {return}
        nav.popViewController(animated: true)
    }
    
    func goto() {
        guard let nav = viewController?.navigationController else {return}
        for controller in nav.viewControllers as Array {
            if controller.isKind(of: MyProfileViewController.self) {
                nav.popToViewController(controller, animated: true)
                break
            }
        }
    }
}
