//
//  MyCarClassDetailInteractor.swift
//  HYDD-driver
//
//  Created Macbook Pro on 20/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyCarClassDetailInteractor: MyCarClassDetailInteractorInputProtocol {
    
    weak var presenter: MyCarClassDetailInteractorOutputProtocol?
    
    func getCars() {
        
    }
    
}
