//
//  MyCarClassDetailViewController.swift
//  HYDD-driver
//
//  Created Macbook Pro on 20/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class MyCarClassDetailViewController: BaseViewController, MyCarClassDetailViewProtocol {

    @IBOutlet weak var labelClass: UILabel!
    @IBOutlet weak var tableViewCars: UITableView!
    var presenter: MyCarClassDetailPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupNavigation()
        setupView()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.tabBarController?.tabBar.isHidden = true
    }
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.navigationController?.tabBarController?.tabBar.isHidden = false
    }
    
    @IBAction func backButtonPressed(_ sender: UIButton) {
        presenter?.goBack()
    }
}

extension MyCarClassDetailViewController: SetupViewController {
    func setupNavigation() {
        navigationController?.setNavigationBarHidden(false, animated: false)
        setNavigationWithLogoAndBackButton().addTarget(self, action: #selector(backButtonPressed(_:)), for: .touchUpInside)
    }
    
    func setupView() {
        tableViewCars.delegate = self
        tableViewCars.dataSource = self
        tableViewCars.register(UINib(nibName: "MyCarTableViewCell", bundle: nil), forCellReuseIdentifier: "MyCarTableViewCell")
    }
    
    func networkRequest() {
        
    }
}

extension MyCarClassDetailViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        presenter?.goto(index: indexPath)
    }
}
extension MyCarClassDetailViewController: UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        guard let count = presenter?.carData?.count else {return 0 }
        return count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableViewCars.dequeueReusableCell(withIdentifier: "MyCarTableViewCell") as? MyCarTableViewCell,
            let data = self.presenter?.carData?[indexPath.row] else {return UITableViewCell()}
        if indexPath.row == 0 {
            labelClass.attributedText = data.type.styled(as: .gibsonRegular_40sp)
        }
        cell.labelCar.attributedText = data.numberPlate.styled(as: .gibsonRegular_16sp)
        cell.imageChevron.isHidden = true
        return cell
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
}
