//
//  SplashPresenter.swift
//  AskWho
//
//  Created Shahzaib Iqbal Bhatti on 8/27/19.
//  Copyright © 2019 Shahzaib Iqbal Bhatti. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashPresenter: SplashPresenterProtocol, SplashInteractorOutputProtocol {

    weak private var view: SplashViewProtocol?
    var interactor: SplashInteractorInputProtocol?
    private let router: SplashWireframeProtocol
    
    private var isTwilioSyncCompleted = false
    private var isSpalashTimeElapsed = false

    init(interface: SplashViewProtocol, interactor: SplashInteractorInputProtocol?, router: SplashWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func makeUserFlow() {
        router.makeUserFlow()
    }
    
    func synchronizeCompleted() {
        isTwilioSyncCompleted = true
        isSpalashTimeElapsed ? router.makeUserFlow() : ()
    }

    func startDownloadingEnglish() {
        self.interactor?.startDownloadingEnglish()
    }
    
    func startDownloadingFrench() {
        self.interactor?.startDownloadingFrench()
    }
    
    func englishJSONDownloadedSuccessfully() {
        self.view?.englishJSONDownloadedSuccessfully()
        self.router.loadViewAfterJSONSetup()
    }
    
    func englishJSONDownloadingFailed() {
        self.view?.englishJSONDownloadingFailed()
    }
    
    func arabicJSONDownloadedSuccessfully() {
        self.view?.arabicJSONDownloadedSuccessfully()
    }
    
    func arabicJSONDownloadingFailed() {
        self.view?.arabicJSONDownloadingFailed()
    }
    
    func switchLangauge(language: String) {
        //Return if user selects language which is already selected
        if language == "English" {
            if "en" == AppLanguage.selectedLanguage {
                return
            }
        } else {
            if "ar" == AppLanguage.selectedLanguage {
                return
            }
        }
        
        self.interactor?.switchLangauge(language: language == "English" ? "en" : "ar")
    }
    
    func languageSwitchedSuccessfully(langauge: String) {
        self.view?.languageSwitchedSuccessfully(langauge: langauge)
    }
}
