//
//  SplashProtocols.swift
//  AskWho
//
//  Created Shahzaib Iqbal Bhatti on 8/27/19.
//  Copyright © 2019 Shahzaib Iqbal Bhatti. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol SplashWireframeProtocol: class {
    func loadViewAfterJSONSetup()
    func makeUserFlow()
}
// MARK: Presenter -
protocol SplashPresenterProtocol: class {

    var interactor: SplashInteractorInputProtocol? { get set }
    
    func startDownloadingEnglish()
    func startDownloadingFrench()
    
    func switchLangauge(language: String)
    func makeUserFlow()
}

// MARK: Interactor -
protocol SplashInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    
    func englishJSONDownloadedSuccessfully()
    func englishJSONDownloadingFailed()
    
    func arabicJSONDownloadedSuccessfully()
    func arabicJSONDownloadingFailed()
    
    func languageSwitchedSuccessfully(langauge: String)
}

protocol SplashInteractorInputProtocol: class {

    var presenter: SplashInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
    func startDownloadingEnglish()
    func startDownloadingFrench()
    func switchLangauge(language: String)
}

// MARK: View -
protocol SplashViewProtocol: class {

    var presenter: SplashPresenterProtocol? { get set }

    /* Presenter -> ViewController */
    func englishJSONDownloadedSuccessfully()
    func englishJSONDownloadingFailed()
    
    func arabicJSONDownloadedSuccessfully()
    func arabicJSONDownloadingFailed()
    
    func languageSwitchedSuccessfully(langauge: String)
}
