//
//  SplashInteractor.swift
//  AskWho
//
//  Created Shahzaib Iqbal Bhatti on 8/27/19.
//  Copyright © 2019 Shahzaib Iqbal Bhatti. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashInteractor: SplashInteractorInputProtocol {
    
    static let apiClient = APIClient()
      var getHelpTask: URLSessionDataTask!

    weak var presenter: SplashInteractorOutputProtocol?
    
    func startDownloadingEnglish() {
        DynamicJSONManager.shared.parseJSONIfDownloaded { (status) in}
    }
    
    func startDownloadingFrench() {
        DynamicJSONManager.shared.parseJSONIfDownloadedFr { (status) in}
    }
    
    func switchLangauge(language: String) {
        AppLanguage.set(selectedLanguage: language)
        self.presenter?.languageSwitchedSuccessfully(langauge: language)
    }
}
