//
//  SplashRouter.swift
//  AskWho
//
//  Created Shahzaib Iqbal Bhatti on 8/27/19.
//  Copyright © 2019 Shahzaib Iqbal Bhatti. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SplashRouter: SplashWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = SplashViewController(nibName: nil, bundle: nil)
        let interactor = SplashInteractor()
        let router = SplashRouter()
        let presenter = SplashPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func loadViewAfterJSONSetup() {
        DispatchQueue.main.async {
//            Bootstrapper.loadViewAfterJSONSetup()
        }
    }
    
    func makeUserFlow() {
        Bootstrapper.makeUserFlow()
    }
    
}
