//
//  NewPasswordRouter.swift
//  HYDD-driver
//
//  Created Syed Kashan on 01/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class NewPasswordRouter: NewPasswordWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(oldPassword: String?) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = NewPasswordViewController(nibName: nil, bundle: nil)
        let interactor = NewPasswordInteractor()
        let router = NewPasswordRouter()
        let presenter = NewPasswordPresenter(interface: view, interactor: interactor, router: router)
        presenter.oldPassword = oldPassword
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func goBack() {
        guard let nav = self.viewController?.navigationController else {return}
        nav.popViewController(animated: true)
    }
}
