//
//  NewPasswordInteractor.swift
//  HYDD-driver
//
//  Created Syed Kashan on 01/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import UIKit

class NewPasswordInteractor: NewPasswordInteractorInputProtocol {
    
    weak var presenter: NewPasswordInteractorOutputProtocol?
    
    static let apiClient = APIClient()
    
    var changePasswordTask: URLSessionDataTask!
    
    func changePassword(para: [String : Any]) {
        guard let id = HUM.shared.user?.id else {return}
        HUM.shared.getToken { isSuccess in
            if isSuccess{
                self.changePasswordTask?.cancel()
                let changeReq = URLRequest(url: NETWORKCONSTANTS.changePassword(id: id),
                                           method: URLRequest.HTTPMethod.put,
                                           body: para)
                self.changePasswordTask = NewPasswordInteractor.apiClient.dataTask(changeReq) {[weak self] response in
                    //Response
                    response.successResponse.flatMap { (data, response) in
                        printHydd("Response is \(data) \nResponse \(response)")
                        printHydd(String(decoding: data, as: UTF8.self))
                        if let dataDictionary = data.getJSONFromData() {
                            if let message = dataDictionary["message"] as? String {
                                HMM.shared.showError(title: DJM.shared.getValue(view: "change_password_view", variable: "error"), message: message)
                                self?.presenter?.failedChanged()
                            } else {
                                HMM.shared.showStatusSuccess(message: DJM.shared.getValue(view: "change_password_view", variable: "pass_success"))
                                self?.presenter?.successChanged()
                            }
                        } else {
                            self?.presenter?.failedChanged()
                        }
                    }
                }
            }
        }
    }
}
