//
//  NewPasswordProtocols.swift
//  HYDD-driver
//
//  Created Syed Kashan on 01/03/2020.
//  Copyright © 2020 Syed Kashan. All rights reserved.
//
//  Template generated by Syed Kashan
//

import Foundation

// MARK: Wireframe -
protocol NewPasswordWireframeProtocol: class {
    func goBack()
}
// MARK: Presenter -
protocol NewPasswordPresenterProtocol: class {

    var interactor: NewPasswordInteractorInputProtocol? { get set }
    var newPassword: String? {get set}
    var oldPassword: String? {get set}
    
    func goBack()
    func set(password: String)
    func actionOK()
}

// MARK: Interactor -
protocol NewPasswordInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func successChanged()
    func failedChanged()
}

protocol NewPasswordInteractorInputProtocol: class {

    var presenter: NewPasswordInteractorOutputProtocol? { get set }

    /* Presenter -> Interactor */
    func changePassword(para: [String: Any])
}

// MARK: View -
protocol NewPasswordViewProtocol: class {

    var presenter: NewPasswordPresenterProtocol? { get set }

    func showLoader()
    func hideLoader()
    func dismissView()
    /* Presenter -> ViewController */
}
